server:
  port: 8080
  error:
    include-message: always
  servlet:
    context-path: /api/chatter

spring:
  application:
    name: Chatter

logging:
  level:
    root: INFO
    # org.springframework: DEBUG  # Uncomment for detailed Spring logs
